server:
  port: 8084

spring:
  application:
    name: rococo-userdata
  grpc:
    server:
      port: 9094
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-userdata'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rococo-userdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: userdata
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: guru.qa.rococo.model

logging:
  level:
    root: INFO
    org.springframework.grpc: DEBUG
    guru.qa.rococo.service.GrpcLoggerInterceptor: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  grpc:
    server:
      port: 9094
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-userdata'
    username: postgres
    password: secret
