server:
  port: 8081

spring:
  application:
    name: rococo-museum
  grpc:
    server:
      port: 9091
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-museum'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rococo-museum
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.grpc: DEBUG
    qa.guru.rococo.service.GrpcLoggerInterceptor: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  grpc:
    server:
      port: 9091
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-museum'
    username: postgres
    password: secret
